### ISSUE TITLE
java.lang.IndexOutOfBoundsException for insert null value into column with 'bigint' type

### ISSUE THREAD

**Issue by AlexanderFar** [Stratio/cassandra-lucene-index#105]
```
CREATE TABLE t (
	id int,
	v bigint,
	lucene text,
	PRIMARY KEY (id) 
);
insert into t json '{"id":1, "v":null}'; -- 1 statement successfully executed

CREATE CUSTOM INDEX licene_index ON t (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'schema' : '{fields : {i_v: {type : "long", 	column: "v" }}}'
};

insert into t(id) values(1); -- 1 statement successfully executed

BUT FOR
insert into t(id,v) values(1,null);
insert into t json '{"id":1}';
insert into t json '{"id":1,  "v":null  }'; 
-- ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.IndexOutOfBoundsException">

insert into t json '{"id":1, "v":1}'; -- 1 statement successfully executed
```

if change type of  column **'v'** on 'int', insert **'null'** value gone fine

**Comment by ealonsodb** [comment]
Which version of cassandra and cassandra-lucene-index are you using??

**Comment by ealonsodb** [comment]
This issue is related to [#94](https://github.com/Stratio/cassandra-lucene-index/issues/94).

It occurs in version [2.2.4.2](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.4.2) but it has been fixed in versions [2.2.4.4](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.4.4), [2.2.5.2](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.5.2) and [3.0.3.1](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.3.1)

Please upgrade your cassandra-lucene-index (and Cassandra if required) to solve it.

Regards

**Comment by AlexanderFar** [comment]
Cassandra 2.2.4

**Comment by AlexanderFar** [comment]
Thanks. All work fine.
