### ISSUE TITLE
Improved integration with Cassandra to remove unneeded lucene re-index run

### ISSUE THREAD

**Issue by AdiLev** [Stratio/cassandra-lucene-index#11]
The scenario I created is an index refresh index every second

There is NO NEED to run this code every second if no access (or dirty access - changes of the date) were done to Cassandra from last build. (Even read only is not consider a dirty access).  
As now this run unnecessary, creating workload on the machine, while no changes or access are done to the Cassandra!!! . 
As you added Lucene to run on the Cassandra itself, you could add a listener/filter code to Lucene/Cassandra refresh loop to disable such runs which is aware of dirtiness or at least for no access.

CREATE INDEX log_os ON sregion.logevent ( os_type );
ON  sregion.logevent (stratio_col) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
      'refresh_seconds':'1', 
      'num_cached_filters':'1',
      'ram_buffer_mb':'64', 
      'max_merge_mb':'5', 
      'max_cached_mb':'30',
      'schema':'{
        default_analyzer:"standard",
        fields:{
                event_code:{type:"string"},
                application:{type:"string"}, 
                event_time:{type:"date", pattern:"yyyy/MM/dd"}, 
                username:{type:"string"}, 
                ip_address:{type:"string"}, 
                os_type:{type:"integer"}, 
                data:{type:"text", 
                analyzer:"english"}}
}';

**Comment by adelapena** [comment]
Hi,

First, I would like to clarify that index refreshing does not imply reindex data. The refresher thread just reopens the current Lucene [IndexSearcher](https://lucene.apache.org/core/5_1_0/core/org/apache/lucene/search/IndexSearcher.html)/[IndexReader](http://lucene.apache.org/core/5_1_0/core/org/apache/lucene/index/IndexReader.html), which contains a snapshot of the index status at the time it was opened.

Also, the index searcher refreshing is performed using a [ControlledRealTimeReopenThread](https://lucene.apache.org/core/5_1_0/core/org/apache/lucene/search/ControlledRealTimeReopenThread.html), which is linked to a Lucene [TrackingIndexWriter](https://lucene.apache.org/core/5_1_0/core/org/apache/lucene/index/TrackingIndexWriter.html). This way, the index searcher reopening only happens if  there have been writes in the index.

Are you experiencing any problem related to this?

Thanks for your interest.
