### ISSUE TITLE
Common questions

### ISSUE THREAD

**Issue by charliy101** [Stratio/cassandra-lucene-index#110]
Hi @adelapena 

I have a few number of common questions regarding Lucene index for Cassandra DB.
How can we manage  Lucene index **within Cassandra DB**?. 
Hear I mean the next possibilities: 
  - review existing Lucene index(indicies) and its structures (like a metadata view)
  - alter existing Lucene index by adding or taking off some columns
  - review status of index (valid or invalid)
  - compression option.

I tried to find answer on questions described above in the documentation, but unfortunately ineffectually.

Could you please answer on them?

Thanks in advance.

**Comment by adelapena** [comment]
Hi @charliy101,

- review existing Lucene index(indicies) and its structures (like a metadata view)
You can use CQL ``DESCRIBE`` command to view the schema of a concrete index, for example ``DESCRIBE INDEX tweets_index ;``, or to get the schemas of the indexes in a keyspace: ``DESCRIBE KEYSPACE demo;``, etc. The [JMX interface](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.4/doc/documentation.rst#jmx-interface) exposes some administrative operations too.

- alter existing Lucene index by adding or taking off some columns
Indexing schema can't be altered due to Lucene's nature. The only way to change the schema is to re-index. You will find the same limitation in other Lucene-based products.

- review status of index (valid or invalid)
What do you mean by valid or invalid?

- compression option
Lucene's codec compression options are not yet customizable.

I hope it helps.

**Comment by charliy101** [comment]
Hi @adelapena.

Some indices like B*tree might become corrupted during the lifecycle and will require rebuild procedure.
How is it going with Lucene index in this case?

Thanks in advance.

**Comment by adelapena** [comment]
As long as I know, Lucene should not be exposed to this kind of corruption. 

Secondary indexes are behind Cassandra's commit log, which is able to automatically replay writes after suddenly power-offs.

However, if you suspect that your index is corrupted in some way, you can use [nodetool rebuild_index](http://docs.datastax.com/en/cassandra/2.0/cassandra/tools/toolsRebuildIndex.html) to rebuilt it.

**Comment by charliy101** [comment]
That's why I asked about the possibility to check whether Lucene index is corrupted or not.
Because If I don't know this, then I am not able to suspect anything ).
Thanks for your help!
