### ISSUE TITLE
Question: Does 'LIMIT' prevents my server from searching all around the nodes?

### ISSUE THREAD

**Issue by EzequielAdrianM** [Stratio/cassandra-lucene-index#125]
Suppose that I have a Big Database containing 100 Million of Users.
The table is distributed along 5 Nodes.

I have Lucene indexing enabled for the 'username' field.

If I make a query to search a user by username (wildcard), also adding LIMIT 30 to the query.
Does this query hit all my nodes?
This query is highly probable to find more than 5 Million users. Does LIMIT save me time? Or cassandra will find everything and then truncate the found list to 30?

**Comment by adelapena** [comment]
Hi @EzequielAdrianM ,

All nodes are hit when you use a top-k query, which is any search containing a *query* or *sort* clause. This is so because the coordinator node needs to retrieve the *k* best results of each node to determine the globally best *k* results.

However, searches containing only a *filter* clause don't need to hit all the nodes. These searches sequentially iterate over the ring until they find the requested number of rows. So the number of hit nodes goes from one in the best case to all in the worst case. You can find an explanation about this [here](http://es.slideshare.net/dhiguero/advanced-search-and-topk-queries-in-cassandracassandrasummiteurope2014), at slides 17 and 18.

Obviously, searches with a CQL restriction in the primary key only touch the node responsible for this key.

This is about hit nodes. Regarding the per-node limit behaviour, there is no in-memory filtering. If you request *k* rows, then the index will only take *k* primary keys, and *k* rows will be read from the SSTables. So yes, a lower limit clause will save time compared to a higher limit.
