### ISSUE TITLE
Sort and paging

### ISSUE THREAD

**Issue by beppeg** [Stratio/cassandra-lucene-index#142]
Hello,
I'm querying a table by PK and index filter and I need to paging the result using Paging State.
All works fine as long as I do not require ordering/sorting.
Using native "ORDER BY " the clustering key does not has effect on normal query, instead returns an incorrect and not ordered result with paging.
Using sort on a indexed column (not the clustered key) I get an Exception:
`Top-k searches don't support paging, so a cautious LIMIT clause should be provided to prevent excessive memory consumption.`
Am I doing something wrong? There are other ways to get the expected result ?

Release is 3.5.1.
Thank you.

**Comment by adelapena** [comment]
Hi @beppeg ,

Paging over sorted results is not supported in Cassandra 3.x. This feature is supported in Cassandra 2.x but we haven't had time to port it to 3.x yet. Paging over sorted results is tricky because Apache Cassandra secondary index API doesn't support it, so we should use a custom CQL query handler to intercept the query and send it to a modified storage proxy. We have plans to enable it very soon, probably in the next release.

**Comment by beppeg** [comment]
Hi Andrés,
thank you for your quick reply. I look forward to your next releases.

**Comment by victorbadila** [comment]
Hi @adelapena 

I am also trying to achieve paging over top-k queries and I have no problem with using Cassandra 2.x at the moment. I checked the documentation for 2.1.14 though and I have found reference only to paging filtered results, not sorted ones (or ideally for my use case both sorted and filtered with a lucene query). I checked this documentation https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.14/doc/src/site/sphinx/documentation.rst#paging

**Comment by adelapena** [comment]
@beppeg, @victorbadila, we are happy to announce that we have just published [cassandra-lucene-index 3.0.6.1](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.6.1), which adds support for paging over sorted results. All future 3.x releases will support this feature.

@victorbadila, paging over sorted results in 2.x [has been available since 2.1.8.1](https://github.com/Stratio/cassandra-lucene-index/blob/3.0.6.1/CHANGELOG.md#2181-31-july-2015).
