### ISSUE TITLE
Java memory tuning

### ISSUE THREAD

**Issue by jrglee** [Stratio/cassandra-lucene-index#154]
It is usual to tune the heap size following this [documentation](https://docs.datastax.com/en/cassandra/3.x/cassandra/operations/opsTuneJVM.html). In a brand new setup we can expect something between 2Gb and 8Gb of heap size. While this setup is great for Cassandra by itself, it looks like I may have to consider a larger heap size to allow Lucene to do its work.

Is there any guideline or recommendations on how to tune the Java heap size? If not can you add it to the documentation?

Thanks

**Comment by adelapena** [comment]
Hi @jrglee,

Sorry for the late response. There is no an easy way determine the optimal heap size aside from empirically. Both indexing and searching memory consumption depends greatly on the specific use case. However, the general rules for Cassandra are still valid for Lucene. The main bottle necks usually are the CPU and the disk when indexing, and the disk when searching. Very large heaps are counterproductive in most cases due to the GC pauses, and you will get better results relying on the OS cache. 

That said, the general recommendation when using Lucene indexes would be to use the plain Cassandra heap config, measure the performance for your use case, and then try slightly greater heap size until you find an optimal.

I hope this helps.
