### ISSUE TITLE
when cassandra upgrade forces reindexing, what are the breaking changes?

### ISSUE THREAD

**Issue by geenalouise** [Stratio/cassandra-lucene-index#170]
What kinds of cassandra changes force a lucene reindexing?  How often will upgrades break the index?  How long would it take to reindex 1 billion documents in a 5 node cassandra cluster?

I am a lucene and elasticsearch expert, so no intro needed.  Thank you so much for your help with this.

...Geena Louise

**Comment by adelapena** [comment]
Hi @geenalouise ,

Reindexing only happens when you manually drop and re-create the secondary index, or when you use [nodetool rebuild_index](https://docs.datastax.com/en/cassandra/3.0/cassandra/tools/toolsRebuildIndex.html). Otherwise, each local Cassandra row write is immediately translated to a single Lucene document write. Cleanup, repair and compact doesn't produce any kind of explicit reindexing.

Compatibility between index versions is broken when there are Lucene upgrades and/or significative improvements in the row-document mapping. You can get an idea of the frequency reviewing the [changelog](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/CHANGELOG.md) and the [compatibility matrix](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#upgrade).

Regarding the time required to reindex 1 billion documents in a 5 node Cassandra cluster, it is hard to say. As you probably know, Lucene indexing speed depends on the hardware specs, and on the number and type of indexed fields. Also, the number of documents to be written should be multiplied by the replication factor. Indexing speed uses to be around a few thousand rows per second, so this kind of reindexing will probably take some hours with 5 regular nodes.

I hope it helps
