### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper at com.stratio.cassandra.lucene.builder.Builder.<clinit>(Builder.java:44)

### ISSUE THREAD

**Issue by ipvpbr** [Stratio/cassandra-lucene-index#175]
Hi,

Congratulations and thanks for all the good work on the amazing cassandra-lucene-index.

I am getting the following NoClassDefFoundError while using  the cassandra-lucene-index-builder:

Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper
	at com.stratio.cassandra.lucene.builder.Builder.<clinit>(Builder.java:44)
.....

The jars were generated  successfully  following the instructions.

Could you please evaluate/consider on future versions to move from the org.codehaus.jackson  to the newer com.fasterxml.jackson?

Thanks
IPVP

**Comment by adelapena** [comment]
Hi @ipvpbr,

Thanks for your interest in the project.

Which version of the builder are you using? We have tested it with an empty Maven local repository without any problem. Could it be a problem with your repo or Maven configuration?

Anyway, you are right about using the newer Jackson version, we have [just upgraded it](https://github.com/Stratio/cassandra-lucene-index/commit/ffe1bfc54b81495a0aced436b86cca9339770d9e) in [3.0.8 branch](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.8). 

However, we will continue with codehaus at server side for a time because we inherit the dependency from Cassandra. Hopefully we will see Apache Cassandra upgraded to the new version of Jackson very soon.

Thanks,
