### ISSUE TITLE
Indexing a Map field with multiple mappers

### ISSUE THREAD

**Issue by kifkif1** [Stratio/cassandra-lucene-index#179]
Hi,

in my C* Map column, I set the type to `map<text,text>` but actually I'd like to store values of different types. Strings, Integers and Double/Long are the types I'm looking for. 
I was looking for a way with the cassandra-lucene-index plugin to index the field multiple times with different mappers. 

Something like (pseudo-code):

```
        fields : {
                ...
            payload : { type : "string"},
            payload : { type : "float"},
            payload : { type : "integer"},
                ...
        }
```
Is this possible? I know that indexing a `text` value with the integer/float mapper would certainly require parsing of the value to the other datatypes (integer/float). 

Or do I have to split up the map<text,text> into three Maps? One for each data type and then index them one by one? 

This solution would introduce some issues when querying because the user that queries would have to know about which map (i.e. "mapInt", "mapFloat", "mapString") he has to query for the attribute. I assume that if the user would not query one of the maps but query on ALL of the three maps, this would impact performance.

My table: 
```
CREATE TABLE test.data (
    id text,
    date text,
    ts timestamp,
    latitude float,
    longitude float,
    payload map<text, text>,
    PRIMARY KEY ((id, date), ts)
) 
```
My lucene index:
```
CREATE CUSTOM INDEX lucene_index ON data ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '60',
    'schema' : '{
        fields : {
            ts  : {type : "date", pattern : "yyyy-MM-dd HH:mm"},
            payload : { type : "string"},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};
```

Thanks again

**Comment by adelapena** [comment]
Hi,

You can assign multiple mappers to a column:
```
fields : {
                ...
            s_payload : { type : "string", column: "payload"},
            f_payload : { type : "float", column: "payload"},
            i_payload : { type : "integer", column: "payload"},
                ...
        }
...
SELECT * FROM data WHERE expr(lucene_index, 
   '{filter: {type: "match", field: "s_payload.a_key", value: "1"}}');
SELECT * FROM data WHERE expr(lucene_index, 
   '{filter: {type: "match", field: "i_payload.some_key", value: 1}}');
```
This is useful to index columns with compatible mappers. For example, you could index a text column as both tokenized and untokenized text. 

However, it seems a bad idea in your use case because the used mappers are not compatible with every possible value of `payload`. In the aforementioned example, `i_payload` will try to map each column value in `payload`, producing a failure per each string or float column. Even though the index [is able to ignore this error mapping errors and make a best-effort mapping](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/plugin/src/main/java/com/stratio/cassandra/lucene/schema/Schema.java#L141), it would produce a unneeded resource consumption, and you would also be forced to implicitly specify the value data type in the searches (see the search examples above). Also, from Cassandra point of view, storing integers and floats serialized as strings can be a waste of resources.

So, IMHO, it is a better idea to use one separate map per data type:
```
CREATE TABLE test.data (
    id text,
    date text,
    ts timestamp,
    latitude float,
    longitude float,
    payload_int map<text, int>,
    payload_float map<text, float>,
    payload_text map<text, text>,
    PRIMARY KEY ((id, date), ts)
);
CREATE CUSTOM INDEX lucene_index ON data ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '60',
    'schema' : '{
        fields : {
            ts  : {type : "date", pattern : "yyyy-MM-dd HH:mm"},
            payload_int : { type : "integer"},
            payload_float : { type : "float"},
            payload_text : { type : "string"},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};
```
Of course this can be transparent for the user, you can have a separate table for knowing the types of the fields and map the user queries at application layer. This is a common pattern that we have successfully used in several projects with users requiring custom fields.

Performance-wise, each map entry is translated to a separate Cassandra cell, and after mapped to a separate Lucene field, so there shouldn't be any performance difference between both approaches, but the performance improvement due to using proper value serialization.
