### ISSUE TITLE
Unrecognized field "sorted" exception in the version 3.0.8.*

### ISSUE THREAD

**Issue by dyangrev** [Stratio/cassandra-lucene-index#182]
Hey, we're trying to upgrade cassandra and the lucene plugin to the new version 3.0.8 today while we see the following errors in the cassandra log when trying to start the cassandra:

```
Caused by: com.stratio.cassandra.lucene.IndexException: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unrecognized field "sorted" (Class com.stratio.cassandra.lucene.schema.mapping.builder.DateMapperBuilder), not marked as ignorable
 at [Source: java.io.StringReader@265dc576; line: 7, column: 29] (through reference chain: com.stratio.cassandra.lucene.schema.mapping.builder.DateMapperBuilder["sorted"]): {
    fields : {
        start_time: {
            type      : "date",
            validated : true,
            pattern   : "yyyy-MM-dd HH:mm:ss",
            sorted    : true
       }
    }
  }
```

we had a date field that we needed sorting on, it was working fine with the previous version of 3.0.7 and 3.0.3 but looked like the version 3.0.8 was having issue with it.

I'm wondering if it's something that has been removed in the new version?

**Comment by adelapena** [comment]
Hi @dyangrev,

The ``sorted`` property [was removed in 3.0.5.1](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/CHANGELOG.md#3051-may-19-2016). Since that version all the mapped fields are always indexed and sorted. This is so because de Lucene [doc values](http://blog.trifork.com/2011/10/27/introducing-lucene-index-doc-values/) that were used only for sorting now are also used for searching, so they should be always created.

Also, the JSON searializer was configured to fail on unknown properties (as ``sorted``) at [3.0.7.2](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/CHANGELOG.md#3072-july-05-2016), as part of some refactorings to simplify the JSON search syntax. This behaviour can be changed [here](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/plugin/src/main/java/com/stratio/cassandra/lucene/util/JsonSerializer.java#L44), if you are interested in.

So you should just remove the ``sorted``property from you schema, the indexed data will be sorted anyway.

I hope that helps,

**Comment by dyangrev** [comment]
Thanks for the replying, we will recreate our index.

**Comment by adelapena** [comment]
You are very welcome

**Comment by ealonsodb** [comment]
Hi @karlbunnell: 

Can you show us the table and index creation sentences please?

**Comment by karlbunnell** [comment]
The only change (when porting from 2.x to 3.x version of the plugin) was to port from the lucene "dummy column" syntax to the new expr() syntax. As mentioned in this issue, I also removed the "sorted : true" attribute as that was causing the plugin to fail at load.  

CREATE TABLE IF NOT EXISTS wss_ear.q_meta_q ( rid varchar, count_type varchar, key_l1 varchar, key_l2 varchar, key_count BIGINT, r_range_start timestamp, r_range_stop timestamp, a_range_start timestamp, a_range_stop timestamp, expire timestamp, cost_bytes DOUBLE ,total_bytes BIGINT ,cs_bytes BIGINT ,hits BIGINT ,page_views BIGINT ,cost_time DOUBLE ,browse_time BIGINT ,sc_bytes BIGINT, PRIMARY KEY ( (rid), count_type, key_l1, key_l2 ))

CREATE CUSTOM INDEX IF NOT EXISTS q_meta_q_index ON wss_ear.q_meta_q () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = { 'refresh_seconds' : '3600', 'schema' : '{ fields : { count_type : {type : "text", analyzer : "english"} ,key_l1 : {type : "text", analyzer : "english"} ,key_l2 : {type : "text", analyzer : "english"}, cost_bytes : {type : "double"} ,total_bytes : {type : "long"} ,cs_bytes : {type : "long"} ,hits : {type : "long"} ,page_views : {type : "long"} ,cost_time : {type : "double"} ,browse_time : {type : "long"} ,sc_bytes : {type : "long"} } } }' }

**Comment by karlbunnell** [comment]
Simplified use case:

CREATE KEYSPACE demo WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE IF NOT EXISTS demo.q_test_q ( lucene text, rid varchar, key_l1 varchar, PRIMARY KEY ( (rid), key_l1));

CREATE CUSTOM INDEX IF NOT EXISTS q_test_q_index ON demo.q_test_q (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = { 'refresh_seconds' : '3600', 'schema' : '{ fields : { key_l1 : {type : "text", analyzer : "english"} } }' };

INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'apple' );
INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'banana' );
INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'cantalope' );
INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'dates' );
INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'elfs' );
INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'figs' );
INSERT INTO demo.q_test_q (rid, key_l1) VALUES ('5cd4bff9-4427-467c-b5ee-2f8bd855d0b7', 'zebras' );


SELECT key_l1 FROM demo.q_test_q WHERE rid = '5cd4bff9-4427-467c-b5ee-2f8bd855d0b7' AND lucene = '{"sort":{"fields":[{"field":"key_l1","reverse":true}]},"refresh":true}';

InvalidRequest: Error from server: code=2200 [Invalid query] message="Field 'key_l1' does not support sorting"

**Comment by adelapena** [comment]
Hi @karlbunnell ,

Text fields as `key_l1` can't be sorted because the tokenization process makes sorting meaningless (which one of the produced tokens should be used for sorting?). 

The old behaviour was to produce a Lucene's single-term [DocValuesField](https://lucene.apache.org/core/5_3_0/core/org/apache/lucene/document/SortedDocValuesField.html) for text mappers with the `sorted`options active, ignoring the analyzer and having the same behaviour than a `string` mapper, which was quite misleading.

Now, you can replicate the old sorting behaviour using a `string` field instead of a `text` one:
```sql
CREATE CUSTOM INDEX IF NOT EXISTS q_meta_q_index 
ON wss_ear.q_meta_q () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
    'refresh_seconds' : '3600', 
    'schema' : '{ 
        fields : { 
            count_type : { type : "text", analyzer : "english"} ,
            key_l1 : {type : "string"} ,
            key_l2 : {type : "text", analyzer : "english"}, 
            cost_bytes : {type : "double"} ,
            total_bytes : {type : "long"} ,
            cs_bytes : {type : "long"} ,
            hits : {type : "long"} ,
            page_views : {type : "long"} ,
            cost_time : {type : "double"} ,
            browse_time : {type : "long"} ,
            sc_bytes : {type : "long"} 
       } 
    }' 
};
SELECT key_l1 FROM demo.q_test_q WHERE rid = '5cd4bff9-4427-467c-b5ee-2f8bd855d0b7' AND lucene = '{"sort":{"fields":[{"field":"key_l1","reverse":true}]},"refresh":true}';
```
Or, if you need both sorting and tokenization, you can use one mapper for each case:
```sql
CREATE CUSTOM INDEX IF NOT EXISTS q_meta_q_index 
ON wss_ear.q_meta_q () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
    'refresh_seconds' : '3600', 
    'schema' : '{ 
        fields : { 
            count_type : { type : "text", analyzer : "english"} ,
            key_l1_t : {type : "text", analyzer : "english", column: "key_l1"} ,
            key_l1_s : {type : "string", column: "key_l1"}, 
            key_l2 : {type : "text", analyzer : "english"}, 
            cost_bytes : {type : "double"} ,
            total_bytes : {type : "long"} ,
            cs_bytes : {type : "long"} ,
            hits : {type : "long"} ,
            page_views : {type : "long"} ,
            cost_time : {type : "double"} ,
            browse_time : {type : "long"} ,
            sc_bytes : {type : "long"} 
       } 
    }' 
};
SELECT key_l1 FROM demo.q_test_q WHERE rid = '5cd4bff9-4427-467c-b5ee-2f8bd855d0b7' AND lucene = '{"sort":{"fields":[{"field":"key_l1_s","reverse":true}]},"refresh":true}';
```
I hope that helps.

**Comment by karlbunnell** [comment]
That makes perfect sense. We can switch to "string" type and be fine. We got caught by the misleading behavior of the 2.x version. Many thanks for your response.

**Comment by banksone** [comment]
Hi is there any way to ignore keyword 'sorted' during schema migration and use old indexes or at least not fail and let me modify indexes after cassandra is up? Without, I had to change indexes on the old db version and migrate after that in case of any fail I would have down both dbs. (just migrating 2.2.x to 3.11
