### ISSUE TITLE
Clarification about actions taken by cassandra-lucene-index upon refresh

### ISSUE THREAD

**Issue by forumjava** [Stratio/cassandra-lucene-index#19]
Hi,

Is there any resource that details how the indexes managed by cassandra-lucene-index. i.e. the actions that the library takes during refresh.

Specifically, i am looking at the behaviour when my indexed map column is updated during the refresh period and if are there any limitations to the number of updates or the read repairs and such.

Also, when i compared the performance of my UPSERT on the indexed column between C* secondary index and the cassandra-lucene-index, i noticed as much as 20% performance degradation for my UPSERTs. Ofcouse, C* secondary index is not an option for us, but would you know how index mgmt is different between the two. I can understand if the cost difference is during read (because we are allowing much more here), but could not figure what that would be the case for my UPSERT.

Thanks for reading.

**Comment by adelapena** [comment]
Indexing implies build a data structure that is stored on disk. Lucene index has with much more features that regular C* secondary indexes, and it's possible writing [a lot of data structures on disk](http://es.slideshare.net/lucenerevolution/what-is-inaluceneagrandfinal). That's because writes on Lucene-indexed tables are much more slow than C* ones, it's the price of expressive indexing.

The index refreshing is not related with write performance. It is the min time between Lucene IndexReader reloads. The IndexReader is reused and not opened in each query in order to speed up queries. 

I hope it helps.

**Comment by forumjava** [comment]
Thanks!
