### ISSUE TITLE
Paging returns nondeterministic results 

### ISSUE THREAD

**Issue by AdamChlupacek** [Stratio/cassandra-lucene-index#198]
Hi,

Recently we have started using lucene for our fulltext search and we have come to an interesting issue while paging through results returned by lucene. It happens that after the first page there is a chance that lucene will not return any more results, appends about first 8 results from the first page and acts as if the query ended. If the page size is increased to cover the whole result set then the result is correct. 

As of now we are using:
Cassandra 3.7
Lucene Index: 3.7

Any help would be much appreciated,
Thanks!

**Comment by adelapena** [comment]
Hi @AdamChlupacek,

We would require some more detailed info in order to reproduce the issue:

- Which specific version of the index are you using? It should be composed by three numbers.
- Could you provide the table schema and the failing query? Some test data to reproduce the problem would be ideal.
- How many nodes does your cluster have? Which replication factor are you using?
- Which fetch size are you using? 

Thanks,

**Comment by AdamChlupacek** [comment]
Hi,

Thanks for the answer.

On friday we found some inconsistencies over our cluster so we run full repair and rebuild of all indexes and seems like that got us rid of this issue. Since we are not able to reproduce this anymore I am closing this issue.
