### ISSUE TITLE
Can I pass Lucene Query Syntax when SELECTing?

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#232]
Example: `(title:"foo bar" AND body:"quick fox") OR title:fox`

**Comment by adelapena** [comment]
No, you can't. There is partial support for Lucene syntax but only for internal debugging purposes:
```
SELECT * FROM a_table WHERE expr(an_index, 
'{filter:{type:"lucene", query: "(title:"foo bar" AND body:"quick fox") OR title:fox"}}');

SELECT * FROM a_table WHERE lucene =  
'{filter:{type:"lucene", query: "(title:"foo bar" AND body:"quick fox") OR title:fox"}}';
```
This syntax doesn't guarantee full support for analyzers, collections, etc. due to Lucene's query parser limitations and shouldn't be used unless you're familiarised with the internal of this project.

**Comment by didip** [comment]
ok, thanks for the speedy reply!
