### ISSUE TITLE
branch-2.1.16 is for 2.1.16 version of casaandra?

### ISSUE THREAD

**Issue by dejwsz** [Stratio/cassandra-lucene-index#238]
Can't see such a branch, will you expose the plugin for this version of Cassandra?

**Comment by adelapena** [comment]
Hi @dejwsz,

The last release for 2.1.x was [2.1.15](https://github.com/Stratio/cassandra-lucene-index/tree/2.1.15.0), targeted to Apache Cassandra 2.1.15. We haven't published a release for 2.1.16.  It probably doesn't make much sense to do so now, given that, as you can read [here](http://cassandra.apache.org/download/):

- Apache Cassandra 2.1 is supported until November 2016 with critical fixes only.

We encourage you to upgrade to Apache Cassandra 3.0.x due to the lack of support for previous releases.

**Comment by dejwsz** [comment]
OK but for some reasons we have to stick with 2.1 for some time and as I can see they published 2.1.16 version recently. But if your plugin in version 2.1.15 will work well then we will use it.

**Comment by adelapena** [comment]
We haven't tested it, it will probably work, given that interfaces shouldn't have changed. 

We will try to test it and throw a new 2.1.16.0 as soon as possible, but I can't give you a date.

**Comment by dejwsz** [comment]
sure thx

**Comment by ealonsodb** [comment]
Hi @dejwsz:
I have just created the [branch-2.1.16](https://github.com/Stratio/cassandra-lucene-index/tree/branch-2.1.16) upgrading cassandra version. We will release 2.1.16.0 version ASAP

**Comment by ealonsodb** [comment]
Hi @dejwsz : 
We have just released [2.1.16.0](https://github.com/Stratio/cassandra-lucene-index/tree/2.1.16.0)

It will be available in maven central soon (usually ~one hour)
Cheers

**Comment by dejwsz** [comment]
thanks!
