### ISSUE TITLE
Syncrhonous indexing clarification

### ISSUE THREAD

**Issue by donaldquixote** [Stratio/cassandra-lucene-index#26]
Apologies if there is a better forum for this question.

Documentation specifies that indexing_threads = 0 means synchronous indexing. Does this mean synchronous with the write to the indexed partition? What implications does this have for index reads? 
For my scenario, if I have:

* A guarantee of at most one writer per partition
* Writer performs multiple (index-based) reads then writes in quick succession

Will each index read reflect all previous writes to the partition, or is there still potential for the index to lag behind?

Thanks.

**Comment by donaldquixote** [comment]
From another (closed issue on this project)

> The index refreshing is not related with write performance. It is the min time between Lucene IndexReader reloads. The IndexReader is reused and not opened in each query in order to speed up queries.

I assume that this might play into any answer provided?

**Comment by adelapena** [comment]
Hi,

Index refreshing means that, given an index with a refresh time ``n``, any writer client must wait at least ``n`` before it could see its own writes. In practice, this wait time is a little bit greater because of the time required by the refresh operation. And this is certainly not related with write performance.

Asynchronous indexing is a different concept that is closely related to write performance. Synchronous writes means that if an index write operation fails, then the whole Cassandra operation will fail. This is obviously a desirable behavior, the problem is that it doesn't fully exploit the parallelism of the processor. In the other hand, asynchronous indexing has a greater performance because of the use of indexing queues. Thus, the problem with async writes is that some kind of indexing errors will not be reported to the clients. Furthermore, there is no way to know when an async index write has been performed. The time spent in queues is usually lower than a second.

I sounds like if your use case requires an quick succession of reads and writes over the same indexed data, then Lucene based solutions are not suitable for you. Most search engines provide [near real time](https://en.wikipedia.org/wiki/Real-time_computing#Near_real-time) search and, if I understand correctly, it's a pure real time use case, unless you can deal with a relatively large delay between writes and reads, maybe a couple of seconds. 

I hope it helps.

**Comment by donaldquixote** [comment]
I was suspecting as much, but needed a more experienced interpretation. Thank you for the quick reply and for your work. We will still make good use of this plugin even without this particular scenario.
