### ISSUE TITLE
Support Facets

### ISSUE THREAD

**Issue by kyleboyle** [Stratio/cassandra-lucene-index#278]
Any thoughts on supporting facets? Here is a brief description of it looks on DSE:

https://docs.datastax.com/en/datastax_enterprise/5.0/datastax_enterprise/srch/queriesCql.html#queriesJSON__solrFacetquery

If it isn't planned by the stratio folks, any tips on how to get started? I'm new to the cassandra secondary index interface.

**Comment by adelapena** [comment]
The problem with faceting is that currently [Apache Cassandra doesn't support distributed/replica side aggregations](https://issues.apache.org/jira/browse/CASSANDRA-8826) due to the problems of reconciliation in the coordinator side. When a row is requested, the coordinator uses the timestamps of the rows returned by each replica to solve conflicts. However, aggregated results (faceting is a particular case) doesn't contain such information, so there is no way to solve conflicts.

**Comment by kyleboyle** [comment]
Would there be a way to not do aggregation and just return multiple rows, one for each vnode. Then the client can aggregate the results if they want
