### ISSUE TITLE
Sometimes, the Lucene index returns very quickly with no results.

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#334]
Observed on Cassandra 3.7. If I run the same query again, it will return results.

There are no errors, just an empty result set. We get about 20% ratio of receiving empty results.

There aren't that many records in the table, slightly less than a million. Lucene should have no problem processing these.

This is the table:

```
CREATE TABLE my_ks.my_table (
    id text PRIMARY KEY,
    app text,
    chunks text,
    dc text,
    suffix text,
    updated bigint
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX idx_my_table ON my_ks.my_table () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '120', 'max_merge_mb': '20', 'ram_buffer_mb': '256', 'max_cached_mb': '1024', 'schema': '{
    fields: {
      id: {type: "string"},
      app: {type: "string"},
      dc: {type: "string"},
      chunks: {type: "text", analyzer: "english"},
      updated: {type: "bigint"}
    }
  }'};
```

This is the typical query:

```
SELECT id, app, dc, suffix FROM my_table WHERE expr(idx_my_table, '{filter: {type: "boolean", must: [{"field":"chunks","type":"contains","values":["first-word"]},{"field":"chunks","type":"contains","values":["second-word"]}]}}') LIMIT 500;
```

The read consistency level is `LOCAL_ONE`

**Comment by ealonsodb** [comment]
Hi @didip: 
Do you write with consistency LOCAL_ALL just before querying?

**Comment by didip** [comment]
All writes are `LOCAL_ONE`. This is a high throughput system so we opted for speed instead of stronger consistency.

Currently, we have a half baked work-around where the app code retries 7 times until it gets results. But this is undesirable.

Another work-around we did is to perform complete index rebuild every week. That seems to help reducing the percentage of empty results.

**Comment by ealonsodb** [comment]
Hi @didip:
Do you write with consistency 'LOCAL_ONE' **just before** querying?

**Comment by didip** [comment]
For this table, write happens in a cronjob every 5 minutes (to syncing new updates, sometimes there are nothing to write), read happens whenever webapp perform queries. So it's possible for write happens before read.

We thought of creating a separate keyspace with higher replication factor (5 for example) and use `LOCAL_QUORUM` when writing. Current keyspace replication factor is 2. Would that help?

**Comment by ealonsodb** [comment]
Hi @didip:

Please read the [refresh_seconds](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.14/doc/documentation.rst#indexing) section in Indexing and [refresh](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.14/doc/documentation.rst#searching) searching option. 

Basically,  inserts data is written into a lucene IndexWriter. Every `refresh_seconds` (in your case 120 secs ) a new indexReader based on that indexWriter data. 

Any client would not see those last inserted records in the last window(120 secs) until that indexReader is recreated. You can force that indexReader recreation using the every query [refresh](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.14/doc/documentation.rst#searching) option. 

So, I think the solution for you would be use the refresh option. This is a costly operation, so , please make sure you don't execute it in every query, (just the first one). 

Were those missed results in the query written recently? In the last 120 secs?

What i dont understand is that you accept a weak consistency (writing with `LOCAL_ONE` reading with `LOCAL_ONE`) but you cannot get empty result? 

What is you writes/reads ratio? If you write once and read multiple it is recommended using consistency `LOCAL_ALL` for writes and `LOCAL_ONE` for reads.

The problem with this is that consistency write level needs all nodes up to full fill the insert. I would try the write with consistency `LOCAL_ALL`and if it fails,  i will retry with consistency `LOCAL_QUORUM`. 

Hope this helps

**Comment by didip** [comment]
Hi @ealonsodb ,

Thank you for the detailed analysis. The missed results are random, sometimes they are from recent inserts, sometimes they are from old inserts (making refresh lag seems unlikely). 

This indicates, as you pointed out, a bad consistency setting. `LOCAL_ALL` for writes and `LOCAL_ONE` for reads sounds like a good idea. We will also play around with different Keyspace because I think for this table, RF 2 is not good enough.

**Comment by ealonsodb** [comment]
Hi @didip: 

So, did you resolve your issue? Could you please close this?

**Comment by didip** [comment]
@ealonsodb ,

Sorry that it took a while to reply.

So we decided to bite the bullet and change things around:

1. Create a new keyspace with RF=5.

2. Migrated all the data, and fully rebuild the indices on those columns.

3. Write is now `LOCAL_QUORUM`, read is still `LOCAL_ONE`. The app talks to the DC it belongs to (we have multi DC setup).

The new setup helps a lot but, rarely now, we still get empty results. I am not sure what else going on now. Are there other things I can do to help you guys debugging?

We didn't change refresh option, it is still 2 minutes. Do you think changing it to 1 minute helps?

**Comment by didip** [comment]
If there's a verbose logging setting that I can turn on, that would be fantastic.

**Comment by ealonsodb** [comment]
Hi @didip: 

This is not a bug. this is the expected behaviour and i will show you why. 

When one write is executed (in one node), the coordinator for that query sends that write to **all other nodes** (in your case with RF=5 to the 5 related nodes), but it only waits the acknowledge return message from the write consistency (in this case LOCAL_QUORUM ==  RF/2 == **3**) number of nodes

This means that if every node in your cluster is up and running and it is not heavy loaded that write with consistency LOCAL_QUORUM would perform just as LOCAL_ALL. Every replica would have the data written.

But if you think about these read/write consistencies in a not so good environment: 

When you write with LOCAL_QUORUM you are sure 3 machines receives that write. 

When you are reading, with LOCAL_ONE, you are asking any node about that data. The java-driver choose one (maybe one **with data**, maybe **not**) and ask it about this query. 

Thats why i suggested to try first to write with LOCAL_ALL (sometimes you are lucky and those 5 nodes receives the write). If this write fails, you should retry with LOCAL_QUROUM and if this fails, with LOCAL_ONE. 

You mentioned `All writes are LOCAL_ONE. This is a high throughput system so we opted for speed instead of stronger consistency.` you prefer speed instead of strong consistency. This issue is all you have, weak consistency. 

You mentioned  a ingestion process that writes every 5 minutes.
You can write with LOCAL_ONE, then perform a cassandra repair process(fixes every data inconsistency) and after that, continue operating. 

For how to activate logging, please read #322

What do you think?

**Comment by didip** [comment]
That makes sense. Thanks again for explaining this further.

Also, thanks for the logging tips. You guys should put that in the docs, I am sure it will help a lot of other people as well.

I will close this ticket.
