### ISSUE TITLE
Range Filter on Date return wrong data 

### ISSUE THREAD

**Issue by mrrfrog** [Stratio/cassandra-lucene-index#339]
**Version**

```
cassandra-lucene-index 2.2.8.0
cassandra 2.2.8
```

**Schema**

```
CREATE CUSTOM INDEX test_lucence_index ON test (lucene) USING 'com.stratio.cassandra.lucene.Index' 
WITH OPTIONS = {
	'refresh_seconds': '60',
	 'schema': '{
		fields : {
			trans_id : { type: "uuid", column: "trans_id"},
			time_request  : {type : "date", pattern   : "yyyy-MM-dd HH:mm"} ,
		} 
	}'
};
```

**Query**

```
SELECT time_request FROM test WHERE lucene =  '{
    refresh:true, 
    filter : {
        type:"range",
        field:"time_request",
        lower:"2017-07-04 09:00",
        upper:"2017-07-04 09:59",
        include_lower: true,
        include_upper: true
        
    }
    
}';
```

**Actual Result**

```
 time_request
--------------------------
 2017-07-04 05:28:00+0000
 2017-07-04 04:45:07+0000

(2 rows)
```

**Expected Result**

```
 time_request
--------------------------
 2017-07-04 09:10:00+0000
 2017-07-04 09:15:20+0000
 2017-07-04 09:16:45+0000
 2017-07-04 09:45:00+0000
 2017-07-04 09:50:03+0000

(5 rows)
```

**Issue Description**

FIlter should return records between time  2017-07-04 09:00 and  2017-07-04 09:59 but its look like the hour and minute filter is not working properly?

**Comment by mrrfrog** [comment]
It's look like index **do not use** the current system **timezone** , I tried to set timezone in pattern and set the timezone in query and it's look like works .

`pattern   : "yyyy-MM-dd HH:mm:ss.SSS Z"`

```
lower:"2017-07-04 09:00:00.000 +0000"
upper:"2017-07-04 09:59:00.000 +0000"
```

**Comment by ealonsodb** [comment]
Hi @baltazar22: 

Yes, you are right, when using date patterns it is advisable to use the timezone to not depend on the coordinator node timezone.  

Indeed, this following paragraph is extracted from [Datastax documentation](http://docs.datastax.com/en/cql/3.3/cql/cql_reference/timestamp_type_r.html): 

`If no time zone is specified, the time zone of the Cassandra coordinator node handing the write request is used. For accuracy, DataStax recommends specifying the time zone rather than relying on the time zone configured on the Cassandra nodes.`

I don't know where but i have read the recommendation to save every datetime in cassandra in UTC(with timezone) and only change the time zone in presentation layer(to user time zone).

Regards

**Comment by ealonsodb** [comment]
Could you pleasse close this issue?
