### ISSUE TITLE
Add new index without dropping existing indexes

### ISSUE THREAD

**Issue by samyem** [Stratio/cassandra-lucene-index#51]
From what I understand, to add a new index on a field, we have to drop the entire custom index and rebuild everything to include the new index. Could addition of new indexes avoid the need to drop existing indexes? This is going to be problematic for large tables.

**Comment by adelapena** [comment]
Unfortunately it's [an Apache Cassandra 2.x design decision](https://github.com/apache/cassandra/blob/cassandra-2.2/src/java/org/apache/cassandra/db/index/SecondaryIndexManager.java#L86), so it's out of the scope of this project. I think that this limitation is going to disappear with [the new secondary index API](https://issues.apache.org/jira/browse/CASSANDRA-9459). If you want this feature in 2.x, you should open an issue at [Apache Cassandra JIRA](https://issues.apache.org/jira/browse/CASSANDRA).

**Comment by samyem** [comment]
Can this not be done like how the "refresh" operation is done via a special select syntax like:
SELECT * FROM tweets WHERE lucene = '{alter-schema:fields {... } }';

The new fields can be added to newer inserts only if that simplifies things. This way, there is no need to drop the entire secondary index isn't it?

**Comment by adelapena** [comment]
It would be problematic because, as long as I know, Lucene doesn't allow to add new fields to existing documents. Most Lucene based products (ElasticSearch, Solr) doesn't allow this kind of schema updates, because this would imply to full-scan the data source and upsert each document. Each upsert is really a deletion followed by a full document insertion. This operation would be equals or slower than creating a new index.

Perhaps it's an interesting feature that could be added in the future, we think that it would be better to wait for Cassandra 3.0 new index API, which allows to create several multi-column indexes in the same table. This new API could also be modified to natively support reindexing.

**Comment by samyem** [comment]
Well practically in most cases there will not be a need to change the fields for existing documents, but it'd be very useful if and when new fields are added to tables, the index can also be adjusted for newer writes. This is especially true for timeseries write-once type of data. With Solr, we were able to add new fields without a full reindex.

**Comment by adelapena** [comment]
Ok, I was understanding that you wanted to add old unindexed columns to the index. Indexing only new columns is much less problematic, so we could add this new feature to 2.x ASAP.

**Comment by avkonst** [comment]
Hi, guys. Nice work. I wonder what the state of this issue with Cassandra 3.x? Is this limitation still actual?

**Comment by adelapena** [comment]
Hi,

Cassandra still doesn't allow to have more than one per-row secondary index per table. However, since [3.0.5.1](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.5.1), you can [create Lucene indexes using old per-column syntax](https://github.com/Stratio/cassandra-lucene-index/blob/3.0.5.1/doc/documentation.rst#alternative-syntaxes). This makes the trick to have so many indexes as you want:
```
CREATE TABLE test (
    pk int,
    ck int,
    rc text,
    lucene1 text,
    PRIMARY KEY (pk, ck)
);

-- Create first index
CREATE CUSTOM INDEX index_1 ON test (lucene1) 
USING 'com.stratio.cassandra.lucene.Index' 
WITH OPTIONS = {
    'refresh_seconds': '1', 
    'schema': '{
       fields : {
          pk  : {type: "long"},
          ck  : {type: "long"},
          rc  : {type: "string"}
       }
    }'
};

-- Insert some data
INSERT INTO test.test (pk, ck, rc) VALUES (1, 1, 'a');
INSERT INTO test.test (pk, ck, rc) VALUES (1, 2, 'b');
INSERT INTO test.test (pk, ck, rc) VALUES (2, 1, 'c');
INSERT INTO test.test (pk, ck, rc) VALUES (2, 2, 'ab');
INSERT INTO test.test (pk, ck, rc) VALUES (3, 1, 'ac');
INSERT INTO test.test (pk, ck, rc) VALUES (3, 2, 'bc');

-- Search into first index with both old and new syntaxes
SELECT * FROM test.test WHERE lucene1 = '{}';
SELECT * FROM test.test WHERE expr(index_1,'{}');

-- Create a second index over new dummy column
ALTER TABLE test ADD lucene2 text;
CREATE CUSTOM INDEX index_2 ON test (lucene2) 
USING 'com.stratio.cassandra.lucene.Index' 
WITH OPTIONS = {
    'refresh_seconds': '1', 
    'schema': '{
       fields : {
          pk  : {type: "long"},
          ck  : {type: "long"},
          rc  : {type: "string"}
       }
    }'
};

-- Search into second index with both old and new syntaxes
SELECT * FROM test WHERE lucene2 = '{}';
SELECT * FROM test WHERE expr(index_2,'{}');
```

**Comment by adelapena** [comment]
I have [just updated](https://github.com/Stratio/cassandra-lucene-index/commit/2ffeb394ef454e9955893dcb984ebeba56c5f5d8) the documentation about this. Thanks!

**Comment by avkonst** [comment]
Thank you very much! Excellent!

**Comment by avkonst** [comment]
'refresh_seconds': '1', -- does it mean that 2 independent indexes will flush to disk every second each and together will touch disk IO twice per second?

**Comment by adelapena** [comment]
No. Flushes to disk are synchronized with the flushes of the indexed table, and they can also occur when the Lucene in-memory write buffer is full. ``refresh_seconds`` is related with reads, it is the max rebuilding frequency of the Lucene's [IndexSearcher](https://lucene.apache.org/core/5_3_0/core/org/apache/lucene/search/IndexSearcher.html). This is an object with a frozen view of the index, and it will be reopened once per second only if there have been writes since the last refresh. So you won't see writes produced in the last second.

Anyway, the ideal scenario is to have a single index per table. The reason for having two indexes at a time is that, if you want to change the index schema, you can attend searches with the old index while building the new one and, once it is built, you can redirect the searches to the new index and drop the old one.
