### ISSUE TITLE
Are miliseconds supported in range filters concerning date fields?

### ISSUE THREAD

**Issue by dejwsz** [Stratio/cassandra-lucene-index#56]
Hi, as I can see the mapping for date field supports such pattern: yyyy/MM/dd HH:mm:ss.SSS Z. So in theory milliseconds (SSS) should be supported. 
When I use range filter it looks like the milliseconds are not taken under consideration. So in case of use of such a filter:
{type:"range", field:"modifytime", lower:"2015-10-27 14:05:39.798"} I can get only these rows which modify time is lower from 2015-10-27 14:05:39.000 (798 ms is considered as 000). Are milliseconds really supported?

**Comment by ealonsodb** [comment]
Hi @dejwsz , 
Yes, milliseconds are supported in range filters. 
By deafult Range query does not include lower or upper bounding

You must set ``include_lower``  to true in order to get results including "2015-10-27 14:05:39.798".

I have executed this simple example and it works ok.

```

CREATE KEYSPACE test 
     WITH replication = {'class':'SimpleStrategy', 'replication_factor': 1};
USE test;

CREATE TABLE test1 (
	id int,
	date timestamp,
	lucene text,
	PRIMARY KEY (id)
);

CREATE CUSTOM INDEX test_index ON test.test1(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            date : {type:"date"}
    }}'
};

INSERT into test.test1(id, date) VALUES (1, '2015-10-27 14:05:39.798');

SELECT * FROM test.test1 
    WHERE lucene='{type:"range", field:"date", 
                                 lower:"2015-10-27 14:05:39.798", 
                                 include_lower:true}';

```

In addition to that, if you want use the default pattern for dates "yyyy/MM/dd HH:mm:ss.SSS Z" please be aware that  'Z' is time zone. 
Instead, if you want to use "yyyy/MM/dd HH:mm:ss.SSS" set it in the mapper so:

```


CREATE CUSTOM INDEX test_index ON test.test1(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            date : {type:"date", pattern:"yyyy/MM/dd HH:mm:ss.SSS"}
    }}'
};

```

**Comment by dejwsz** [comment]
OK I will add upper include and see. Thanks!
