### ISSUE TITLE
Sort by Distance

### ISSUE THREAD

**Issue by badhriappadoodle** [Stratio/cassandra-lucene-index#60]
Hello,
From #34, just noticed that sort by distance is in your development roadmap.
Could you please let me know when this functionality will be released.

Cheers.

**Comment by adelapena** [comment]
As you have said, this issue is repeated. Pease don't open new issues about the same topic. 
Sort by distance is still in our roadmap but we can't give you a release date. In the mean time, maybe you could use a distance search to retrieve all the nearest items and sort them in client or using a C* UDF, if your use case allows it. Anyway, pull requests are welcome :)

**Comment by ealonsodb** [comment]
Hi @badhriappadoodle, please look at new news about this in issue #34
