### ISSUE TITLE
Support mixed case on wildcard matches

### ISSUE THREAD

**Issue by minauser** [Stratio/cassandra-lucene-index#65]
Hi,

I use plugin 2.1.10. Please see below for the information on CREATE INDEX, CREATE KEYSPACE, CREATE TABLE, INSERT and SELECT:

CREATE KEYSPACE IF NOT EXISTS my_keyspace WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};

USE my_keyspace;

CREATE TABLE IF NOT EXISTS my_table(id uuid, name varchar, lucene TEXT, PRIMARY KEY(id));
INSERT INTO my_table(name, id) VALUES ('TestName', 1c3d775f-d251-448f-9d51-5f3e0689ff0c);
CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds' : '1',
   'schema' : '{
      fields : {
         id : {type : "uuid"},
         name : {type : "string", case_sensitive: false}
      }
   }'
};

If I run

SELECT * FROM my_table WHERE lucene = '{filter: { type: "wildcard", field: "name", value: "T*" }}';

it returns nothing.

If I change my query to 

SELECT * FROM my_table WHERE lucene = '{filter: { type: "wildcard", field: "name", value: "t*" }}';

it returns 1 row.

Looks like that mixed case on wild card matches is not supported. Is the same behavior in 2.1.11? 
Your suggestion on how to run mixed case on wildcard matches (after case_sensitive is set to false) is appreciated.

Kindest regards,
Mina

**Comment by ealonsodb** [comment]
This is not an issue, it is the expected behaviour. 

By default in Lucene, Wildcard, Prefix and Fuzzy queries are not passed through the analyzer, which is the component that performs operations such as stemming and lowercasing. 

So if you set case_sensitive to false in the mapper, all the data is lowercased before indexed so your queries must be in lowercase to be able to get the indexed rows.

Regards
