### ISSUE TITLE
Return number of matched rows and paging like Elasticsearch or Solr

### ISSUE THREAD

**Issue by sunchanras** [Stratio/cassandra-lucene-index#7]
There is no number of matched rows when you do search, only return rows. for example: a query criteria might match 1000 of rows but we only need to get return 10 rows, then we do paging by offset rows by 10 for each time like ElasticSearch and Solr.

**Comment by adelapena** [comment]
Indeed this kind of paging would be a nice feature, but I am afraid that this would require several changes in Apache Cassandra paging system in order to do it more generic. The problem is that Cassandra does paging assuming that index implementations would return rows ordered by their primary key. We have plans to propose changes in this sense at Cassandra's JIRA as soon as possible. In the mean time, you only can use [Cassandra regular paging](http://www.datastax.com/dev/blog/client-side-improvements-in-cassandra-2-0) with those queries that only contain a ``filter`` clause.

**Comment by sunchanras** [comment]
Thank @adelapena. It would be great to have paging like Elasticsearch or Solr on Cassandra. Hope this feature will be added soon.

**Comment by adelapena** [comment]
We have just added experimental full support for automatic CQL paging, even for queries and sorts. With the new CQL handler you can page over search results in the same way it is done with regular Cassandra queries:
```
String query = "SELECT * FROM tweets WHERE lucene='{query:{type:"match", field:"age", value:18}}'";
Statement stmt = new SimpleStatement(query);
stmt.limit(10000);
stmt.setFetchSize(100);
ResultSet rs = session.execute(stmt);

// Iterate over the ResultSet here 
```
This way the results are returned hundred by hundred, and should be enough to present a paged search result view. Offset based paging could be really tricky in distributed systems, so we have no immediate plans to support it.

The changes have been done in [master branch](https://github.com/Stratio/cassandra-lucene-index/tree/master), and they will be present in the next release.

I hope it helps.
