### ISSUE TITLE
Can't search for word 'by'

### ISSUE THREAD

**Issue by nlacey** [Stratio/cassandra-lucene-index#86]
I cant filter using the word 'by'

DROP KEYSPACE IF EXISTS demo3;
CREATE KEYSPACE demo3 WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
USE demo3;

CREATE TABLE test (
id text PRIMARY KEY,
data text,
lucene text
);

CREATE CUSTOM INDEX test_index2 ON test(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
'refresh_seconds' : '1',
'schema' : '{
fields : {
"data" : { type : "text"}
}
}'
};
insert into test (id,data) values ('1234','hi');
insert into test (id,data) values ('1235','hi by')

SELECT * FROM test WHERE lucene='{ filter : { type : "match",field : "data", value : "hi"} }';

 id   | data  | lucene
------+-------+--------
 1234 |    hi |   null
 1235 | hi by |   null

(2 rows)

SELECT * FROM test WHERE lucene='{ filter : { type : "match",field : "data", value : "by"} }';

 id | data | lucene
----+------+--------

(0 rows)

**Comment by ealonsodb** [comment]
Hi @nlacey, this is the expected beahaviour.

There are difference between a string mapper and a text mapper. 

With Text mapper all string inputs goes through an analyzer that eliminates stop words (prepositions,etc..) and prefixes and suffixes and store the rest of the value. The default analyzer is EnglishAnalyzer which has 'by' in its stop words list. 


String mapper uses a Keyword analyzer that just indexes the whole string value as a single token. 


So, in your case, you have two options:

1.- Index with a string mapper 
```
CREATE CUSTOM INDEX test_index2 ON test(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
	'refresh_seconds' : '1',
	'schema' : '{
		fields : {
			"data" : { type : "string"}
		}
	}'
};
```

and select by a wildcard query: 

```
SELECT * FROM test WHERE lucene='{ filter : { 	type : "wildcard",
												field : "data", 
												value : "*hi*" }}';

SELECT * FROM test WHERE lucene='{ filter : { 	type : "wildcard",
												field : "data", 
												value : "*by*" }}';
```

2.- Alternatively you can keep using a text mapper but using the included in lucene 5.3.0 [WhitespaceAnalyzer](https://lucene.apache.org/core/5_3_0/analyzers-common/org/apache/lucene/analysis/core/WhitespaceAnalyzer.html) that only tokenizes the value by spaces without removing neither stopwords nor prefixes or suffixes. 

```
CREATE CUSTOM INDEX test_index2 ON test(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
	'refresh_seconds' : '1',
	'schema' : '{
		fields : {
			"data" : { 	
				type : "text",
				analyzer  : "org.apache.lucene.analysis.core.WhitespaceAnalyzer"}
		}
	}'
};
```

And use match queries

```
SELECT * FROM test WHERE lucene='{ filter : { 	type : "match",
												field : "data", 
												value : "hi" }}';

SELECT * FROM test WHERE lucene='{ filter : { 	type : "match",
												field : "data", 
												value : "by" }}';
```

Best Regards

**Comment by nlacey** [comment]
Thanks for the awesome answer!

**Comment by maxim5** [comment]
Hi @ealonsodb!

Thanks for detailed answer. Is there a doc that could help to pick the right analyzer?
In our case the analyzer should accept texts of any length and tokenize by all space and punctuation symbols.
Some sources (e.g. this StackOverflow answer - http://stackoverflow.com/questions/5483903/comparison-of-lucene-analyzers) suggest using `org.apache.lucene.analysis.standard.ClassicAnalyzer`.
As far as I can see from the tests, it doesn't work as we expect. See the code below:

```
CREATE CUSTOM INDEX demo_index ON demo ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '10',
   'schema': '{
      fields: {
         id: {type: "integer"},
         content: {type: "text", analyzer: "org.apache.lucene.analysis.standard.ClassicAnalyzer"}
      }
   }'
};

insert into demo (id, content) values (0, 'foo bar baz');
insert into demo (id, content) values (1, 'FileNameBar');
insert into demo (id, content) values (2, 'Some text, foo');
insert into demo (id, content) values (3, 'foo:Bar. ABC-DEF');
insert into demo (id, content) values (4, 'foo/bar/baz.abc(def)');

SELECT * FROM demo WHERE expr(demo_index, '{query: {type: "phrase", field: "content", value: "bar", slop: 0}}') LIMIT 10;
--- returns 0, 3, 4, which is what expected

SELECT * FROM demo WHERE expr(demo_index, '{query: {type: "phrase", field: "content", value: "baz", slop: 0}}') LIMIT 10;
--- returns only 0, but not 4

SELECT id FROM demo WHERE expr(demo_index, '{query: {type: "phrase", field: "content", value: "baz", slop: 0}}') LIMIT 10;
--- returns no rows at all
```

**Comment by ealonsodb** [comment]
Hi @maxim5:
Could you tell us which versions(cassandra and cassandra-lucene-index) you are using?
Cheers

**Comment by maxim5** [comment]
Cassandra 3.5, Lucene Index is just built from the sources, according to the sources 3.5.0. Thanks!

**Comment by adelapena** [comment]
Hi @maxim5,

I have reproduced the example and the last query returns row 1. Indeed, the search is exactly the same as in the second query, but requesting only the ``id`` column:
```
cqlsh:demo> SELECT id FROM demo WHERE expr(demo_index, '{query: {type: "phrase", field: "content", value: "baz", slop: 0}}') LIMIT 10;

 id
----
  0
```
Maybe you have thrown the query before the rows are indexed? The refresh frequency is ten seconds...

The third row, ``foo/bar/baz.abc(def)``, doesn't match the term ``baz`` because [Lucene's classic analyzer](https://lucene.apache.org/core/5_3_0/analyzers-common/org/apache/lucene/analysis/standard/ClassicAnalyzer.html) uses a [ClassicTokenizer](https://lucene.apache.org/core/5_3_0/analyzers-common/org/apache/lucene/analysis/standard/ClassicTokenizer.html) that considers a dot that's not followed by whitespace as part of a token, as you can read in [classic tokenizer documentation](https://lucene.apache.org/core/5_3_0/analyzers-common/org/apache/lucene/analysis/standard/ClassicTokenizer.html). So, both the following queries match the row containing ``foo/bar/baz.abc(def)``:
```
SELECT * FROM demo WHERE expr(demo_index, '{query: {type: "match", field: "content", value: "baz.abc"}}');
SELECT * FROM demo WHERE expr(demo_index, '{query: {type: "phrase", field: "content", value: "baz.abc", slop: 0}}');
```
By the way, Lucene's classic analyzer is prebuilt so you can use this briefer syntax:
```
CREATE CUSTOM INDEX demo_index ON demo()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '10',
   'schema': '{
      fields: {
         id: {type: "integer"},
         content: {type: "text", analyzer: "classic"}
      }
   }'
};
```
I hope that helps.

**Comment by maxim5** [comment]
Thanks @adelapena. It's helpful indeed.

- I've tried the query several times, even restarted Cassandra. I don't think it's the update time.
- Yes, I thought so that it's a feature of the tokenizer, not a bug. I'm looking for the easiest way to split the tokens just by punctuation. Providing my own tokenizer is an option too. But I just wanted to know what you guys recommend.

**Comment by adelapena** [comment]
You should create a custom analyzer and put it in Cassandra's ``lib`` folder in order to have it on classpath. You could find this interesting: http://stackoverflow.com/questions/15235126/lucene-4-1-how-split-words-that-contains-dots-when-indexing

By the way, this issue is closed and addresses an unrelated topic. Please create new issues for new topics or reopen related ones in order to ease issues management.
