### ISSUE TITLE
count(*) giving different output

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/cassandra-lucene-index#92]
Hi,
I have a table with more than 15 million records, its been running for a long time and working fine. But when i was using the following query 
`
SELECT count(*) FROM tweets WHERE lucene='{query :  {type : "boolean"
,
                        must : [
                               {type : "match", field : "col1", value :"132"},
                               {type : "match", field : "col2", value :"35"}]}}' ;`

It returned 5562 count, so i executed another query,
`SELECT count(*) FROM tweets  WHERE col1='132' AND col2='35';`
 It returned 60502 as count. Cassandra version i am using is 2.1.7 . 
Once i migrated the data into a test server the behavior was same . Once i dropped and recreated the index again the issue was fixed. What will be the possible reason for this? refresh_second i provided is 1s.

**Comment by adelapena** [comment]
Hi,

How are your table and index schemas? Which version of the plugin are you using?

**Comment by justinjoseph89** [comment]
Hi,
i am using version 2.1.7 , 
`CREATE TABLE tweets (
	col1 text,
	col2 text,
	col3 text,
	col4 text,
	col5 text,
	col6 text,
	col7 text,
	col8 text,
	col9 text,
	col10 text,
	col11 text,
	col12 int,
	col13 text,
	col14 text,
	col15 text,
	col16 text,
	col16 text,
	lucene text,
	PRIMARY KEY (col1,col2,col3,col4,col5)
);`

and index,

`CREATE CUSTOM INDEX IF NOT EXISTS index_name ON tweets (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds' : '1',
'schema' : 
'{ fields : { 
	col1 : {type : "string",sorted:true}, 
	col2 : {type : "string",sorted:true},
	col3 : {type : "string",sorted:true}, 
	col4 : {type : "string"}, 
	col5 : {type : "string"}, 
	col8 : {type : "string",sorted:true},
	col9 : {type : "string",sorted:true},
	col10 : {type : "string",sorted:true},
	col11 : {type : "string"},
	col12 : {type : "string",sorted:true},
	col16 : {type : "string"} 
}}'};`

**Comment by adelapena** [comment]
Oh, I know why you are getting wrong results. 

Your search contains a ``query``clause, which sorts results by Lucene relevance formula, being a particular case of top-k query. Unfortunately, [versions prior to 2.1.8.1 doesn't support paging for top-k queries](https://github.com/Stratio/cassandra-lucene-index/blob/2.1.8.1/CHANGELOG.md). 

So you should upgrade to a release greater or equal than 2.1.8.1 (ideally [2.2.5.0](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.5.0)). 

Alternatively, if you are not interested in relevance sorting, you can use a **filter** clause instead of **query**:
```
SELECT count(*) FROM tweets WHERE lucene=
'{filter : {type : "boolean" , must : [
   {type : "match", field : "col1", value :"132"}, 
   {type : "match", field : "col2", value :"35"}]
}}' ;
```
Additionally, both solutions (upgrading and using filters instead of queries) will improve search performance.

**Comment by justinjoseph89** [comment]
ok thanks .
